--
-- Name: category_entity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_entity (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: category_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_entity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_entity (
    id bigint NOT NULL,
    moment timestamp without time zone,
    order_status integer,
    client_id bigint
);


--
-- Name: order_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item_entity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item_entity (
    price double precision,
    quantity integer,
    product_id bigint NOT NULL,
    order_id bigint NOT NULL
);


--
-- Name: payment_entity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_entity (
    moment timestamp without time zone,
    order_id bigint NOT NULL
);


--
-- Name: product_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: product_entity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_entity (
    id bigint NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255),
    price double precision NOT NULL
);


--
-- Name: product_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_entity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_entity (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


--
-- Name: user_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_entity category_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_entity
    ADD CONSTRAINT category_entity_pkey PRIMARY KEY (id);


--
-- Name: order_entity order_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_entity
    ADD CONSTRAINT order_entity_pkey PRIMARY KEY (id);


--
-- Name: order_item_entity order_item_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_entity
    ADD CONSTRAINT order_item_entity_pkey PRIMARY KEY (order_id, product_id);


--
-- Name: payment_entity payment_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_entity
    ADD CONSTRAINT payment_entity_pkey PRIMARY KEY (order_id);


--
-- Name: product_category product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: product_entity product_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_entity
    ADD CONSTRAINT product_entity_pkey PRIMARY KEY (id);


--
-- Name: user_entity user_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_pkey PRIMARY KEY (id);


--
-- Name: product_category fk11hbgb2km7wyekpq4jtxpjwmu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT fk11hbgb2km7wyekpq4jtxpjwmu FOREIGN KEY (product_id) REFERENCES public.product_entity(id);


--
-- Name: order_item_entity fke17bu5pl07v13gm6pxjw8l87e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_entity
    ADD CONSTRAINT fke17bu5pl07v13gm6pxjw8l87e FOREIGN KEY (product_id) REFERENCES public.product_entity(id);


--
-- Name: order_item_entity fkfok8dv4hj3mw9wixok1qq15xr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_entity
    ADD CONSTRAINT fkfok8dv4hj3mw9wixok1qq15xr FOREIGN KEY (order_id) REFERENCES public.order_entity(id);


--
-- Name: order_entity fkmehcerdvs73r6le9r6j9a14eh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_entity
    ADD CONSTRAINT fkmehcerdvs73r6le9r6j9a14eh FOREIGN KEY (client_id) REFERENCES public.user_entity(id);


--
-- Name: product_category fkmvdusxciw9mmmfxidscrcm2qn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT fkmvdusxciw9mmmfxidscrcm2qn FOREIGN KEY (category_id) REFERENCES public.category_entity(id);


--
-- Name: payment_entity fks9jd9ixl1hxad19q5ywjw4rqs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_entity
    ADD CONSTRAINT fks9jd9ixl1hxad19q5ywjw4rqs FOREIGN KEY (order_id) REFERENCES public.order_entity(id);


--
-- PostgreSQL database dump complete
--

